### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by mendesv1t** [luizferreira7/othello#1]
- [x] Personalizar nomes de jogadores
- [x] Implementar Botão de reiniciar jogo
   - [x] Criar botão
   - [x] Adicionar funcionalidade
- [x] Verificar vitória do jogador
- [x] Pensar numa forma melhor de colocar nossos nomes pq tava feio
   - [x] Passar o mouse no titulo renderiza os nomes
   - [x] Implementar menu com nomes
- [x] Bug: texto de vez do jogador segue aparecendo após clicar no botão reiniciar
- [x] Melhorar estilização do placar pra uma tabela mais suave
- [x] Ajustar posição do placar para lado esquerdo e botão reiniciar para o lado direito
   - [x] Reiniciar no lado direito
   - [x] Placar no lado esquerdo
- [x] Ajustar botão de escolha de modo para centralizado (está torto)
- [x] Repensar sobre plano de fundo (está quebrando no final do site):
     - [x] Uma possível solução: diminuir o tamanho do tabuleiro
     - [x] Ou mudar para uma cor fixa (verde degradê talvez?)
- [x]  Nossa IA está burra, tem que ver se há possibilidade de melhorar (está impossível completar o tabuleiro)
